# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Draw points.
#'
#' @param total_points Total number of points to draw.
#' @param draw_points_lambda Function to draw the points.
#' @param lambda_max Upper bound to lambda.
#'
#' @useDynLib compp
#' @import Rcpp
draw_points_cpp <- function(total_points, draw_points_lambda, lambda_max) {
    .Call('_compp_draw_points_cpp', PACKAGE = 'compp', total_points, draw_points_lambda, lambda_max)
}

